FROM python:3.11-slim
WORKDIR /app

COPY bot_requirements.txt ./
COPY bot/ ./bot/

RUN pip install --no-cache-dir -r bot_requirements.txt &&  \
    apt-get clean &&  \
    apt-get autoremove

ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

# Run the bot
CMD ["python3", "bot/bot.py"]
