FROM python:3.10-slim
WORKDIR /app

# Copy only the necessary files
COPY bot_requirements.txt ./
COPY bot/ ./bot/

RUN apt-get update && apt-get install -y \
    libglib2.0-0 libgobject-2.0-0 libnss3 libnssutil3 libnspr4 \
    libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libx11-6 \
    libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 \
    libgbm1 libxcb1 libxkbcommon0 libasound2 libexpat1 libatspi2.0-0 \
    wget gnupg curl && \
    apt-get clean

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r bot_requirements.txt &&\
    playwright install

# Set environment variables (use a .env file in production)
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

# Run the bot
CMD ["python3", "bot/bot.py"]
