version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name:
      redis
    env_file:
      - ../.envs/.dev
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USER} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    ports:
      - "6379:6379"
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    restart: always
    volumes:
      - /srv/redis:/data
    networks:
      - dev
    hostname: redis

  postgres:
    image: postgres:latest
    env_file:
      - ../.envs/.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name:
      postgres
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - dev
    volumes:
      - /srv/psql:/var/lib/postgresql/data
    restart: always
    hostname: postgres

  dev_bot:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.envs/.dev
    image:
      dev_bot
    container_name:
      dev_bot
    ports:
      - "6012:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev
    volumes:
      - ../:/usr/src/app
    restart: always
    command: bash -c 'uvicorn main:app --proxy-headers --host 127.0.0.1'
    depends_on:
      - postgres
      - redis
    hostname: dev_bot

  tg-bot-tracker:
    build:
      context: ../
      dockerfile: Dockerfile-telegram
    env_file:
      - ../.envs/.dev
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    image:
      tg_bot
    container_name:
      tg_bot
    networks:
      - dev
    volumes:
      - ../:/usr/src/app
    restart: always


networks:
  dev: { }